# AI-Powered Credit Risk & Loan Default Prediction System
## Phase 1: Data Preprocessing

### Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

print('Libraries imported successfully!')

Libraries imported successfully!

### Load Dataset

In [5]:
df = pd.read_csv('D:/Office/group task/AI-Powered-Credit-Risk-Loan-Default-Prediction-System/loan_default_project/data/Loan_default.csv')

print(f'Dataset loaded successfully!')
print(f'Total Rows    : {df.shape[0]:,}')
print(f'Total Columns : {df.shape[1]}')

Dataset loaded successfully!
Total Rows    : 255,347
Total Columns : 18

### Understand Columns

In [6]:
print("--- Dataset Information ---")
df.info()

print("\n--- Statistical Summary ---")
df.describe()

--- Dataset Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  object
 14  HasDependents   255347 non-null  object
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  object
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 35.1+ MB

--- Statistical Summary ---

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00
mean,43.50,82499.30,127578.87,574.26,59.54,2.50,13.49,36.03,0.50,0.12
std,14.99,38963.01,70840.71,158.90,34.64,1.12,6.64,16.97,0.23,0.32
min,18.00,15000.00,5000.00,300.00,0.00,1.00,2.00,12.00,0.10,0.00
25%,31.00,48825.50,66156.00,437.00,30.00,2.00,7.77,24.00,0.30,0.00
50%,43.00,82466.00,127556.00,574.00,60.00,2.00,13.46,36.00,0.50,0.00
75%,56.00,116219.00,188985.00,712.00,90.00,3.00,19.25,48.00,0.70,0.00
max,69.00,149999.00,249999.00,849.00,119.00,4.00,25.00,60.00,0.90,1.00

### Remove IDs

In [7]:
df = df.drop(columns=['LoanID'])

print("Remaining Columns in the Dataset:")
print(df.columns.tolist())

Remaining Columns in the Dataset:
['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner', 'Default']

### Handle Missing Values

In [8]:
missing_values = df.isnull().sum()
print("Missing Values per Column:")
print(missing_values)

Missing Values per Column:
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

### Remove Duplicates

In [9]:
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_count}")

if duplicate_count > 0:
    df = df.drop_duplicates()
    print("Duplicates successfully removed.")

Number of duplicate rows found: 0

### Fix Data Types & Standardize Categories

In [10]:
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip()

print("Data types checked and categories standardized.")

Data types checked and categories standardized.

### Encode Categories

In [11]:
binary_cols = ['HasMortgage', 'HasDependents', 'HasCoSigner']
for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

multiclass_cols = ['Education', 'EmploymentType', 'MaritalStatus', 'LoanPurpose']
df = pd.get_dummies(df, columns=multiclass_cols, drop_first=True)


df.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,HasMortgage,HasDependents,HasCoSigner,Default,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other
0,56,85994,50587,520,80,4,15.23,36,0.44,1,1,1,0,False,False,False,False,False,False,False,False,False,False,False,True
1,69,50432,124440,458,15,1,4.81,60,0.68,0,0,1,0,False,True,False,False,False,False,True,False,False,False,False,True
2,46,84208,129188,451,26,3,21.17,24,0.31,1,1,0,1,False,True,False,False,False,True,False,False,False,False,False,False
3,32,31713,44799,743,0,3,7.07,24,0.23,0,0,0,0,True,False,False,False,False,False,True,False,True,False,False,False
4,60,20437,9139,633,8,4,6.51,48,0.73,0,1,0,0,False,False,False,False,False,True,False,False,False,False,False,False

### Check Outliers

In [12]:
numerical_cols = ['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio']

print("--- Outlier Detection using IQR ---")
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
   
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"{col}: Found {len(outliers)} outliers.")

--- Outlier Detection using IQR ---
Age: Found 0 outliers.
Income: Found 0 outliers.
LoanAmount: Found 0 outliers.
CreditScore: Found 0 outliers.
MonthsEmployed: Found 0 outliers.
NumCreditLines: Found 0 outliers.
InterestRate: Found 0 outliers.
LoanTerm: Found 0 outliers.
DTIRatio: Found 0 outliers.

### Final Review

In [13]:

print(f"Final Dataset Shape: {df.shape}")

df.info()

Final Dataset Shape: (255347, 25)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Age                           255347 non-null  int64
 1   Income                        255347 non-null  int64
 2   LoanAmount                    255347 non-null  int64
 3   CreditScore                   255347 non-null  int64
 4   MonthsEmployed                255347 non-null  int64
 5   NumCreditLines                255347 non-null  int64
 6   InterestRate                  255347 non-null  float64
 7   LoanTerm                      255347 non-null  int64
 8   DTIRatio                      255347 non-null  float64
 9   HasMortgage                   255347 non-null  int64
 10  HasDependents                 255347 non-null  int64
 11  HasCoSigner                   255347 non-null  int64
 12  Default                       255347 non-null  int64
 13  Education_High School         255347 non-null  bool
 14  Education_Master's            255347 non-null  bool
 15  Education_PhD                 255347 non-null  bool
 16  EmploymentType_Part-time      255347 non-null  bool
 17  EmploymentType_Self-employed  255347 non-null  bool
 18  EmploymentType_Unemployed     255347 non-null  bool
 19  MaritalStatus_Married         255347 non-null  bool
 20  MaritalStatus_Single          255347 non-null  bool
 21  LoanPurpose_Business          255347 non-null  bool
 22  LoanPurpose_Education         255347 non-null  bool
 23  LoanPurpose_Home              255347 non-null  bool
 24  LoanPurpose_Other             255347 non-null  bool
dtypes: bool(12), float64(2), int64(11)
memory usage: 28.2 MB

### Save Clean Dataset

In [14]:
df.to_csv('Cleaned_Loan_Default.csv', index=False)

print("Preprocessing complete! The file has been saved as 'Cleaned_Loan_Default.csv'.")

Preprocessing complete! The file has been saved as 'Cleaned_Loan_Default.csv'.